name: xwrf-dev
channels:
  - nodefaults
  - conda-forge
dependencies:
  - dask
  - donfig
  - furo
  - jupyterlab
  - metpy
  - myst-nb
  - netcdf4
  - pint-xarray
  - pip
  - pooch
  - pydantic
  - python=3.9
  - sphinx-autobuild
  - sphinx-autosummary-accessors
  - sphinx-comments
  - sphinx-copybutton
  - sphinx-design
  - xarray>=0.18,!=0.20.0,!=0.20.1
  - xgcm
  - numba
  - hvplot
  - geoviews
  - pip:
      - sphinxext-opengraph
      - autodoc_pydantic
      - -r ../requirements.txt
      - -e ..
